tunnel: YOUR_TUNNEL_ID
credentials-file: /etc/cloudflared/YOUR_TUNNEL_ID.json

ingress:
  - hostname: mistral.seu-dominio.com
    service: http://localhost:8000
  - hostname: api.seu-dominio.com
    service: http://localhost:8001
  - service: http_status:404