version: '3'

services:
  mistral:
    image: mistralai/mistral-instruct:latest
    container_name: mistral
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=${MISTRAL_MODEL:-mistralai/Mistral-7B-Instruct-v0.2}
      - PORT=${MISTRAL_PORT:-8000}
      - HOST=${MISTRAL_HOST:-0.0.0.0}
    volumes:
      - ./models:/models
      - ./cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-carlosdev}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: mistral-api-bridge
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MISTRAL_URL=http://mistral:8000
      - API_PORT=8001
    depends_on:
      - mistral

volumes:
  postgres_data:
  models:
  cache: